version: "2"

services:
  grpc-node:
    container_name: 'grpc-node'
    build: .
    environment:
      GRPC_ENV: 'dev'
      GRPC_VERBOSITY: 'DEBUG'
      CHAIN_WS_ENDPOINT: 'ws://35.234.35.49:9944/'
    ports:
      - '50051:50051'
    networks:
      - app_net
    command: ["node","server.js"]
networks:
  app_net:
    external: true